name: radiobrowser
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.0 <3.0.0'


dependencies:
  http: ^0.13.4
  json_annotation: ^4.3.0
  uuid: ^3.0.5

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.1
